* Update compile&run scripts to use `camomilla` * Remove `simplify_error.py`

diff --git a/example/cf2_primus_clang b/example/cf2_primus_clang
--- a/example/cf2_primus_clang
+++ b/example/cf2_primus_clang
@@ -14,4 +14,10 @@ time clang++ -std=c++14 \
         -lsfml-system \
         -lsfml-graphics \
         -lsfml-window \
-        $1 -o /tmp/x.x && echo "Compiled." && primusrun /tmp/x.x "${@:2}"
+        $1 -o /tmp/x.x |& camomilla
+
+if [ $? == 0 ]; then
+    echo "Compiled." && primusrun /tmp/x.x "${@:2}"
+else
+    echo "Failed."
+fi
